server:
  port: 8082
spring:
  application:
    name: collaboration
  profiles:
    active: local
  sleuth:
    sampler:
      percentage: 1.0
  kafka:
    bootstrap-servers: localhost:9092

swagger.basePackage: top.zhacker.ddd.collaboration.api

spring.datasource.url: jdbc:mysql://127.0.0.1:3306/iddd_collaboration?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
spring.datasource.username: root
spring.datasource.password: anywhere
