spring:
  profiles:
    active: local
  application:
    name: identity-access
  jpa:
    show-sql: true
    database: mysql
  sleuth:
    sampler:
      percentage: 1.0

# spring.jpa.hibernate.ddl-auto: update
#event.store: spring-jdbc
#event.publish.tracker: spring-jdbc

app.name: identity-access

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true

swagger.basePackage: top.zhacker.ddd.identity.api

server:
  port: 8081

#debug: true
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'


---
spring.profiles: local

spring.datasource.url: jdbc:mysql://127.0.0.1:3306/iddd_iam?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
spring.datasource.username: root
spring.datasource.password: anywhere

#spring:
#  rabbitmq:
#    host: 127.0.0.1

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

spring:
  kafka:
    bootstrap-servers: mq.host:9092


---
spring.profiles: ecs

spring.datasource.url: jdbc:mysql://data.host:3306/iddd_iam?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
spring.datasource.username: root
spring.datasource.password: anywhere

#spring:
#  rabbitmq:
#    host: mq.host

spring.cloud.stream.kafka.binder.zkNodes: data.host
spring.cloud.stream.kafka.binder.brokers: mq.host

eureka:
  client:
    service-url:
      defaultZone: http://data.host:8761/eureka/